global-styling:
  version: VERSION
  css:
    theme:
      css/style.css: {}
      css/bootstrap.min.css: {}
      css/flexslider.css: {}
      css/owl.carousel.min.css: {}
      css/owl.theme.default.min.css: {}
  js:
    js/main.js: {}
    js/bootstrap.bundle.min.js: {}
    js/jquery.flexslider-min.js: { minified: true }
    js/jquery.flexslider.js: {}
    js/owl.carousel.min.js: {}
  dependencies:
    - core/jquery