training.desktop:
  label: Landscape
  mediaQuery: 'all and (min-width: 992px)'
  weight: -1
  multipliers:
    - 1x
training.small:
  label: Tablet
  mediaQuery: 'all and (max-width: 991px)'
  weight: -2
  multipliers:
    - 1x
training.mobile:
  label: Mobile
  mediaQuery: 'all and (max-width: 767px)'
  weight: -3
  multipliers:
    - 1x
